export const classical_music_pieces = [
  "Claude Debussy - Clair de Lune",
  "Johann Sebastian Bach - Brandenburg Concertos",
  "Antonio Vivaldi - The Four Seasons",
  "George Frideric Handel - Messiah",
  "Henry Purcell - Dido and Aeneas",
  "Johann Pachelbel - Canon in D",
  "Wolfgang Amadeus Mozart - Symphony No. 40 in G minor",
  "Ludwig van Beethoven - Symphony No. 5 in C minor",
  "Franz Joseph Haydn - String Quartet Op. 76, No. 3 'Emperor'",
  "Wolfgang Amadeus Mozart - Piano Concerto No. 21 in C major",
  "Ludwig van Beethoven - Piano Sonata No. 14 'Moonlight'",
  "Pyotr Ilyich Tchaikovsky - Symphony No. 6 'Pathétique'",
  "Franz Schubert - Symphony No. 8 'Unfinished'",
  "Frédéric Chopin - Nocturnes",
  "Johannes Brahms - Violin Concerto in D major",
  "Giuseppe Verdi - La Traviata",
  "Maurice Ravel - Boléro",
  "Igor Stravinsky - The Rite of Spring",
  "Béla Bartók - Concerto for Orchestra",
  "Sergei Rachmaninoff - Piano Concerto No. 2",
  "John Williams - Theme from 'Schindler's List'",
  "Philip Glass - Glassworks",
  "Arvo Pärt - Spiegel im Spiegel",
  "Steve Reich - Music for 18 Musicians",
  "Eric Whitacre - Lux Aurumque"
]